---
- name: Configure {{package_name}}
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  notify: "{{ item.handler }}"
  with_items:
    - { src: 'my.cnf.j2', dest: '/etc/mysql/my.cnf', handler: 'Restart {{package_name}}'}
    - { src: 'conf.d/mysql.cnf.j2', dest: '/etc/mysql/conf.d/mysql.cnf', handler: 'Restart {{package_name}}'}
    - { src: 'conf.d/mysqldump.cnf.j2', dest: '/etc/mysql/conf.d/mysqldump.cnf', handler: 'Restart {{package_name}}'}
    - { src: 'mysql.conf.d/mysqld.cnf.j2', dest: '/etc/mysql/mysql.conf.d/mysqld.cnf', handler: 'Restart {{package_name}}'}
    - { src: 'mysql.conf.d/mysqld_safe_syslog.cnf.j2', dest: '/etc/mysql/mysql.conf.d/mysqld_safe_syslog.cnf', handler: 'Restart {{package_name}}'}

- name: Create Default User
  mysql_user:
    name: "{{ mysql_user_name }}"
    host: 'localhost'
    password: "{{ mysql_user_password }}"
    priv: '*.*:ALL,GRANT'
    state: present
  when: mysql_user_name != mysql_root_username

- name: Copy user-my.cnf file with password credentials.
  template:
    src: "user-my.cnf.j2"
    dest: "{{ mysql_user_home }}/.my.cnf"
    owner: "{{ mysql_user_name }}"
    mode: 0600
  when: >
    mysql_user_name != mysql_root_username
   


...