apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace.name }}
data:
  nginx.conf: |
    events {
    }
    http {
      server {
        listen {{ .Values.service.targetPort }} ;
    
        location / {
            proxy_pass  http://localhost:8080/;
        }
        location /nginx-health {
          access_log off;
          return 200 "healthy\n";
        }
      }
    }
    
